### ISSUE TITLE
Can I decrypt with public key only or without storing passphrase in app

### ISSUE THREAD

**Issue by simkessy** [wwwtyro/cryptico#16]
Hey I'm a little confused about how I should proceed with my application and using this library: 

I have a web application running on a site with a unique ID. The application takes the ID, plays around with it and calls that a `challenge_code`. 

The `challenge _code` is sent to me (user emails it to me). I encrypt  it and call it a `license_key`. I send that to the application user and he enters the key into the application. 

When the app loads, I need to decrypt the key back into the `challenge_code` and ensure that it matches the `challenge_code` the application would generate. 

I'm not sure what I need to store in the application and what I need to keep on my end of things to ensure that this process works reliably, if at all.

Is it possible to decrypt in the application using only the PublicKey String? I'm trying to avoid storing the passphrase in code.

**Comment by NicolasMassart** [comment]
I think you talk about signature, not encryption.
This can be done using RSA keys: use your private key (protected with a passphrase) to sign and the key used to verify signature is the public key stored in you app.

**Comment by simkessy** [comment]
I was able to solve this using a version of this library with the pull request here: https://github.com/wwwtyro/cryptico/pull/3

Basically I'm creating the RSA key need to decrypt outside my application. I'm converting the key into json then a string. I store that string in my application. Then when I need to decrypt a value, I convert that string back into a RSA Key and can use that to decrypt. It seems to be working pretty well.
