### ISSUE TITLE
Use pbkdf's standard to generate keys from passphrases

### ISSUE THREAD

**Issue by coyotte508** [wwwtyro/cryptico#4]
pbkdf1 example: http://crypto.stackexchange.com/questions/1842/how-does-pbkdf1-work

Currently Crypto++ supports key generation using pbkdf, pbkdf1, pbkdf2. It'd be nice to have at least one of those available here, so that apps written in C++ and javascript are compatible.

**Comment by coyotte508** [comment]
I really made a fool of myself there, misunderstood a lot of stuff. Sorry.

**Comment by wwwtyro** [comment]
This isn't a bad idea -- it would be great to have more compatibility with other cryptosystems.
